'on': push

jobs:
  main:
    runs-on: self-hosted
    strategy:
      matrix:
        sleep: [10, 11, 12, 13]
    steps:
      - uses: actions/checkout@v2

      - uses: ./

      - run: sleep ${{ matrix.sleep }}

      - uses: ./
        with:
          fail-fast: true
