'on': push

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sleep: [10, 11, 12, 13]
    steps:
      - uses: actions/checkout@v2

      - uses: ./

      - run: sleep ${{ matrix.sleep }}

      - id: is-first
        uses: ./

      - run: test "$IS_FIRST_RUN" = "true"
        env:
          IS_FIRST_RUN: ${{ steps.is-first.outputs.is-first-run }}
